apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: datagrid-monitoring
  namespace: rest-cache
spec:
  endpoints:
    - basicAuth:
        username:
          key: username
          name: basic-auth
        password:
          key: password
          name: basic-auth
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
        serverName: certificate-CN
  namespaceSelector:
    matchNames:
      - rest-cache
  selector:
    matchLabels:
      app: datagrid-service
      clusterName: cluster-name