apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  replicas: 1
  expose:
    type: LoadBalancer
  service:
    type: DataGrid
    sites:
      local:
        name: NYC
        expose:
          type: LoadBalancer
      locations:
      - name: LON
        url: openshift://api.cluster-cph-26ba.cph-26ba.example.opentlc.com:6443
        secretName: lon-token
      - name: NYC
        url: openshift://api.cluster-cph-26ba.cph-26ba.example.opentlc.com:6443
        secretName: nyc-token