== Preface - What happens when you run your applications distributed, scaled and in the cloud ...
:experimental:

You are a developer or an architect creating world-class applications and solutions. Well, all apps don't necessarily live in just one box, and for the recent past, Cloud is not only one more computer but a lot more. All applications use a network to communicate with each other, whether they connect to a database, a web service or storage, or other services. 

Creating a distributed application means one has to take specials care of latency, performance, and, most importantly, the responsiveness to the end-users. End users could be systems or humans; what's important is that you have a timely and consistent response. There are a lot many things one can do to optimize the stack. Most importantly, this workshop focuses on one thing i.e., Red Hat Data Grid.

What is Red Hat Data Grid? 
Red Hat Data Grid 8.0 provides a distributed in-memory, NoSQL datastore solution. Your applications can access, process, and analyze data at in-memory speed to deliver a superior user experience. Whether you are using legacy applications or a new breed of microservices and functions, Red Hat Data Grid 8.0 will enable your applications to perform better with its in-memory solution. 


This lab offers attendees an intro-level, hands-on session with Red Hat Data Grid. From the first line of code to making services to consuming them and finally to assembling everything and deploying it on Openshift. It illustrates what Cache is, how to program with a distributed cache, and how to build applications and best practices on designing applications with Cache.

Deploying and maintaining microservices can become challenging. There are many elements of software design one needs to ensure in constructing and maintaining distributed services. To help us deploying our microservices, we are going to use Openshift, a Kubernetes distribution from Red Hat. Kubernetes (commonly referred to as "K8s") is an open-source system for automating deployment, scaling, and management of containerized applications that was originally designed by Google and donated to the Cloud Native Computing Foundation. It aims to provide a "platform for automating deployment, scaling, and operations of application containers across clusters of hosts". In this workshop, we are using a specific distribution of K8s named OpenShift that provide a few sets of features beneficial to maintain our microservices. We use Openshift in this lab because of the complexity involved when dealing with multiple microservices, their updates, downtimes, and so on.

This is a BYOL (Bring Your Own Laptop) session. You will be provided with a CodeReady Workspace, an Openshift environment all pre-provisioned. If you prefer to run locally on your laptop, you can do development on your laptop. Still, you will need to use the provided Openshift environment as Operators installed for you are already set up there. So bring your Windows, OSX, or Linux laptop. You need JDK 8+ on your machine, and Apache Maven (3.5+).

What you are going to learn:

What is Red Hat Data Grid 8.0

What is a Cache, and how to start with the common use cases

What is an Embedded Cache

What is Clustering in a Cache scenario and how it works

What is a Remote Cache and how to take benefit of Red Hat Data Grid

You will build applications with known frameworks like Quarkus and Spring.

You will learn how to use the Red Hat Data Grid server REST API.

You will learn how to externalize sessions.

And many more…​

[NOTE]
====
Don't expect to complete this lab in 3 hours; it will take you a lot more. But that's not a big deal. Pick the topic you want, learn what you want, and come back later to learn more.
====

